Feat/precommit lint
CaseLabJS/CaseLab2024-team1 pull request #10
Opened 2024-10-27 20:24 UTC by Slumrag

Настроил линтер и форматер. Настроил huskey теперь перед каждым комитом будет запускатся линтер и форматер.
Добавил скрипты для форматирования и линта всего проекта.
Пока текущий код не форматировал, но чем раньше, тем лучше.

Ещё конфиг prettier немного поменял. Добавил `;` в конце строки и символ  переноса новой строки CRLF

2024-10-28 09:45 UTC, gineff commented
Лучше не рефакторить чужие ветки, а делать замечания на этапе ревью и просить доработки
Также ветка создается для решение конкретно задачи, эта, в частности, создана для настойки lint и precommit и другой функционал затрагивать не должна

2024-10-28 09:54 UTC, IvanBelikov commented
> создана для настойки lint и precommit и другой функционал затрагивать не должна

Здесь согласен. Лучше не размазывать зону ответственности в рамках задачи

2024-10-28 09:56 UTC, IvanBelikov requested changes
Стоит отменить коммит с вынесением sharedTypes в отдельные модули т.к. это не предполагается в рамках задачи.

2024-10-28 09:56 UTC, gineff requested changes

2024-10-28 09:56 UTC, gineff commented on .prettierrc
> +  "singleQuote": true,
В телеге договаривались о других настройках. В частности "semi": false,. Из-за этого в ветку попали файлы, у которых изменено только форматирование. Мне кажется, не стоит коммитить файлы только ради кавычек и двоеточий

2024-10-28 09:56 UTC, gineff commented on src/stories/Header.tsx
> +    <header>
Так как используем MUI, лучше использовать AppBar + Toolbar, воздержаться от использования нативных компонентов и заменить их компонентами MUI, div - Box, h1 - Typigrapy

2024-10-28 09:56 UTC, gineff commented on src/stories/Header.tsx
> +          <svg
Лучше вынести svg в отдельный файл-модуль и импортировать

2024-10-28 09:56 UTC, gineff commented on .storybook/main.ts
> -import type { StorybookConfig } from "@storybook/react-vite";
не стоит включать файл в коммит только из-за изменений форматирования

2024-10-28 09:56 UTC, gineff commented on .storybook/preview.ts
> -import type { Preview } from "@storybook/react";
так же

2024-10-28 09:56 UTC, gineff commented on src/main.tsx
> -import { StrictMode } from 'react'
Изменения не соответствуют задаче ветки

2024-10-28 09:56 UTC, gineff commented on src/router/index.tsx
> -import { createBrowserRouter } from 'react-router-dom'
Изменения не соответствуют задаче ветки

2024-10-28 09:56 UTC, gineff commented on src/shared/types/index.ts
> +export type { Document } from './Document/Document';
Изменения не соответствуют задаче ветки, спорный рефакторинг

2024-10-28 09:56 UTC, gineff commented on src/stores/DocumentStore.ts
> -import { makeAutoObservable } from 'mobx'
неверные настройки prettier

2024-10-28 09:56 UTC, gineff commented on src/stores/UIStore.ts
> -import { makeAutoObservable } from 'mobx'
неверные настройки prettier

2024-10-28 09:56 UTC, gineff commented on src/stores/UserStore.ts
> -import { makeAutoObservable } from 'mobx'
Изменения не соответствуют задаче ветки

2024-10-28 09:56 UTC, gineff commented on src/stories/Button.tsx
> -import React from 'react';
Изменения не соответствуют задаче ветки

2024-10-28 09:56 UTC, gineff commented on src/stories/Header.tsx
> +          <h1>Acme</h1>
`<Typograpy component="h1"`>

2024-10-28 09:56 UTC, gineff commented on src/stories/Page.tsx
Изменения не соответствуют задаче ветки

2024-10-28 09:56 UTC, gineff commented on src/theme/ThemeProvider/ThemeProvider.tsx
> +import { ThemeProvider as MUIThemeProvider } from '@mui/material/styles';
Лучше попросить автора втеки, самому сделать исправления

2024-10-28 09:56 UTC, gineff commented on vite.config.ts
> +import tsconfigPaths from 'vite-tsconfig-paths';
Отлично, не знал что так можно

2024-10-28 20:14 UTC, Slumrag commented
Откатил комиты с рефакториногом и линтом существующего кода. Стоит отдельную ветку создать для линта всего кода?
 В конфиге prettier считаю что `;` стоит оставить, это позволит избежать багов, т.к. Prettier при `semi:false`не всегда корректно вставляет `;`.
 Вот пример из документации: https://prettier.io/docs/en/rationale#semicolons

2024-10-29 19:33 UTC, gineff approved these changes

2024-10-29 19:49 UTC, IvanBelikov commented on vite.config.ts
> -  },
Почему был удалён алиас?

2024-10-29 19:54 UTC, Slumrag commented on vite.config.ts
> -  },
Он не удалён, сделал через плагин tsconfigPaths, чтобы алиасы можно было настраивать только в 1 месте. 
До этого одни и те же алисы повторялись в двух конфигах(vite и typescript).

2024-10-29 19:56 UTC, IvanBelikov approved these changes

2024-10-29 19:56 UTC, IvanBelikov commented on vite.config.ts
> -  },
Хорошо

2024-10-31 10:35 UTC, merged