Feature/users store
CaseLabJS/CaseLab2024-team1 pull request #16
Opened 2024-10-31 21:07 UTC by IvanBelikov

1. Реализован юзер стор
2. Немного поменял типы у ручек userController (согласовали с @gineff )
3. Внёс свойство "endOfLine": "crlf" в .prettierrc. Иначе просто не получалось сделать коммит т.к. Prettier по умолчанию ставит LF (согласовали с @Slumrag )

2024-10-31 21:34 UTC, gineff requested changes

2024-10-31 21:34 UTC, gineff commented on src/stores/UserStore/UserStore.ts
> +  users: User[] = []
нужно добавить обработку статуса асинхронного запроса this.loading
и обработку ошибок try {} catch (error) { this.error = error }

2024-10-31 21:34 UTC, gineff commented on src/stores/UserStore/UserStore.ts
> +
можно рассмотреть вариант добавить стор для отдельного пользователя (Можно найти пример реализации Todo App на Mobx, там список задач и задача два разных стора)
const fetchedUsers = await userControllerApi.getUsers()
this.users = fetchedUsers.map((userData) => new User(userData));
Тогда при изменении user не нужно будет updateUserAtUsers

2024-10-31 21:34 UTC, gineff commented on src/stores/UserStore/types.ts
> +export enum SystemRole {
где используется?

2024-11-01 14:38 UTC, IvanBelikov commented on src/stores/UserStore/UserStore.ts
> +  users: User[] = []
Вынес обработку  статуса асинхронного запроса и обработку ошибок в отдельную функцию executeWithLoading.

2024-11-01 14:41 UTC, IvanBelikov commented on src/stores/UserStore/UserStore.ts
> +
Разбил стора на 2. UsersListStore хранит инстансы стора UserStore в поле users.

Вынес методы update, path, addRole, removeRole в UserStore. Сreate и delete остались в UsersListStore.

2024-11-01 14:42 UTC, IvanBelikov commented on src/stores/UserStore/types.ts
> +export enum SystemRole {
Планировалось реализовать компьютед свйоство юзеров-админов. По итогу не стал добавлять данный геттер. Файл удалил.

2024-11-01 15:21 UTC, clue1essdev approved these changes

2024-11-01 18:41 UTC, Sparkell72 approved these changes

2024-11-01 18:41 UTC, merged