Feature/admin panel
CaseLabJS/CaseLab2024-team1 pull request #17
Opened 2024-11-01 15:38 UTC by tv-tugova

![Снимок экрана 2024-11-01 182337](https://github.com/user-attachments/assets/c3656fe1-e1a7-4a35-a23c-b1b975344402)
Реализована самая ранняя версия AdminPage.
Для таблицы использовала компонент DataGrid, так что есть сортировка и поиск внутри столбцов и другие возможности. По кнопке "Добавить пользователя" может открываться страница создания и редактирования юзера (задача @Sparkell72 ). На странице будут еще как минимум компоненты header и footer.
Жду правок и предложений о том, какой еще функционал можно добавить.

2024-11-01 17:08 UTC, IvanBelikov requested changes

2024-11-01 17:08 UTC, IvanBelikov commented on src/components/userTable/userTable.tsx
Данный компонент не входит в цели данной задачи. Его нужно будет убрать.

2024-11-01 17:08 UTC, IvanBelikov commented on src/router/routes.tsx
>          path: ROUTES.admin('document-type'),
AdminPage нужно переложить в родительское element свойство.

2024-11-01 17:08 UTC, IvanBelikov commented on src/components/adminPage/adminPage.tsx
> +    </Paper>
Компонент должен рендерить Header и Footer (сейчас пока можно поставить заглушки). Между ними должен быть <Outlet /> для рендера дочерних страниц.

 Также нужно вставить компонент `<Authorization requireAuth />`

2024-11-01 17:08 UTC, IvanBelikov commented on package.json
> +    "@mui/x-data-grid": "^7.22.0",
Добавление данной зависимости не входит в задачу. Нужно убрать.

2024-11-01 17:11 UTC, IvanBelikov commented on src/components/adminPage/adminPage.tsx
> +    </Paper>
Так же компоненты именуем с заглавной буквы.

2024-11-01 17:20 UTC, IvanBelikov requested changes

2024-11-01 17:20 UTC, IvanBelikov commented on src/router/routes.tsx
> -      },
С учётом того, что родительский компонент у нас `<Authorization />` нужно вернуть данный роут и в свойство element положить AdminPage

2024-11-02 19:50 UTC, tv-tugova commented on src/router/routes.tsx
> -      },
Сделала

2024-11-02 19:54 UTC, tv-tugova commented on src/components/adminPage/adminPage.tsx
> +    </Paper>
Добавлены заглушки Header и Footer

2024-11-02 20:00 UTC, tv-tugova commented on src/components/userTable/userTable.tsx
UserTable теперь доступен по ссылке users. Дальше @Sparkell72 будет работать с этим компонентом.

2024-11-03 07:55 UTC, IvanBelikov approved these changes

2024-11-03 16:52 UTC, Sparkell72 approved these changes

2024-11-03 17:53 UTC, lena-lis approved these changes

2024-11-03 18:12 UTC, merged