Case lab js/feature/create user cabinet
CaseLabJS/CaseLab2024-team1 pull request #20
Opened 2024-11-02 10:27 UTC by glush-chenko

- The registration form has been added
![image](https://github.com/user-attachments/assets/0bd750a3-108f-4fd6-8dd7-864717e02dbd)

- Added toolpadProvider
- The form creation page is integrated with the personal account
![image](https://github.com/user-attachments/assets/b6e4d193-9f4c-456d-b9a4-977fcb80e3db)

- The styles have changed

2024-11-03 18:58 UTC, IvanBelikov approved these changes
Общая рекомендация: разбивать PR на более мелкие подзадачи (пул реквесты). Сложно дать качественный фидбек по PR из-за большого количества изменений.

2024-11-04 07:07 UTC, gineff commented
Игнорируется правила форматирование prettier, неужели ide  не подсвечивает ошибки форматирования?
Не исправлены ошибки eslint (ide так же не подсвечивает ошибки eslint?)

2024-11-04 09:15 UTC, gineff requested changes

2024-11-04 09:15 UTC, gineff commented on src/components/createDocumentForm/createDocumentForm.tsx
![image](https://github.com/user-attachments/assets/7af060e5-bf58-4a4d-ac07-0bf579156ecc)

2024-11-04 14:12 UTC, gineff commented on src/assets/rb_1741.png
600 kb это много для иконки

2024-11-04 21:48 UTC, glush-chenko commented on src/components/appDashboardLayout/page/page.tsx
> +import Box from '@mui/material/Box'
это сделано для того, чтобы страницы имели одинаковые padding в app

2024-11-05 10:29 UTC, IvanBelikov requested changes
С учётом правок Андрея, предлагаю разбить данный PR на несколько мелких. Лучшим вариантом для этого будет создание новых веток от main и подтягивание в них нужных коммитов с помощью `git cherry-pick`

2024-11-10 22:07 UTC, glush-chenko commented
закрыт в связи с разбитием на отдельные ПР

2024-11-10 22:07 UTC, closed without merging