Feature/footer
CaseLabJS/CaseLab2024-team1 pull request #21
Opened 2024-11-02 13:34 UTC by lena-lis

![localhost_5173_](https://github.com/user-attachments/assets/d65be8c8-f2c0-48f2-ad83-96f14d06c196)

Добавлен динамичный футер, который изменяется в зависимости от роли пользователя: если роль `ADMIN`, то отображаются логотип, ссылка на документацию и текущий год; если роль `USER`, то логотип, ссылка на часто задаваемые вопросы и текущий год. 
Для получения данных о пользователе используется UserStore.

Буду рада вашим замечаниям и код-ревью) Если понадобится, то внесу изменения.

2024-11-02 15:27 UTC, clue1essdev commented on src/components/footer/footer.tsx
> +  const { userData } = userStore
Сегодня был влит authStore, там содержатся свойства isAuth и isAdmin, поэтому импортировать роль можно оттуда, и уберется необходимость проводить дополнительные вычисления с помощью some, плюс isAdmin - это булево значение, то есть нет необходимости прописывать role.nane 'ADMIN' и менять его, если что-то изменится, меньше hardcoded значений. Плюс так логичнее, учитывая, что ты в комментарии указываешь "пользователь входит в ЛК, проверяем его роли" - в authStore записывается роль сразу при аутентификации.

2024-11-02 16:44 UTC, lena-lis commented on src/components/footer/footer.tsx
> +  const { userData } = userStore
Исправила. Теперь роль импортируется из authStore

2024-11-03 17:41 UTC, tv-tugova approved these changes

2024-11-03 19:10 UTC, IvanBelikov requested changes

2024-11-03 19:10 UTC, IvanBelikov commented on src/components/footer/footer.tsx
> +
Лучше убрать пропсы у данного компонента и работать с authStore просто через инпут, чтобы избежать излишних импортов при работе с компонентом футера.

2024-11-03 19:11 UTC, IvanBelikov commented on src/components/footer/footer.tsx
Как вариант: создать index.ts, чтобы сократить импорт с `@/components/footer/footer` до `@/components/footer`

2024-11-04 07:17 UTC, lena-lis commented on src/components/footer/footer.tsx
Думаю, что index.ts в случае с футером может быть излишним, ведь у компонента только один файл

2024-11-04 07:18 UTC, lena-lis commented on src/components/footer/footer.tsx
> +
Поправила

2024-11-04 12:27 UTC, IvanBelikov approved these changes

2024-11-05 12:25 UTC, clue1essdev approved these changes

2024-11-05 12:54 UTC, merged