Feature/attribute
CaseLabJS/CaseLab2024-team1 pull request #25
Opened 2024-11-05 10:12 UTC by AlphaRasch

2024-11-05 10:39 UTC, IvanBelikov requested changes

2024-11-05 10:39 UTC, IvanBelikov commented on src/pages/CreateAttribute/index.tsx
Стор по работе с атрибутами сейчас находится в PR. Сейчас нужно подтянуть себе ветку document-type-store (или дождаться пока дойдёт до main). И реализовать страницу с использованием данного стора.

2024-11-06 20:41 UTC, Slumrag commented on src/pages/CreateAttribute/index.tsx
Стоит переименовать папку чтобы она совпадала с названием компонента CreateAttributePage

2024-11-06 20:46 UTC, Slumrag commented on src/pages/CreateAttribute/index.tsx
Сам компонент очень громоздкий. Вынеси элементы страницы в отдельные компоненты Заголовок, форма, сообщение об ошибке.

2024-11-10 18:01 UTC, closed without merging