refactor: :recycle: Added CreateUser component based on @Sparkell72 #22 PR
CaseLabJS/CaseLab2024-team1 pull request #26
Opened 2024-11-05 12:03 UTC by clue1essdev

Refactored given code, added CreateUser component, added CreateUser to routes.tsx

Изменения по сравнению с первоначальным коммитом:
- удален themeProvider;
- удалена кнопка для изменения темы; изменен type поля ввода id на number, стейт userId по умолчанию устанавливает в ноль, а не в строку поля объекта для отправки на сервер в функции handleSubmit id и role закомментированы, поскольку 
1) role принимает не строку, а массив
2) сервер на данный момент игнорирует оба;
- поля удалены ненужные комментарии;  - компонент перемещен в соответствующую папку с соответствующим названием;
- компонент добавлен в router;
- компонент обернут в observer;
- к функции handleSubmit прикручен createUser из userListStore

2024-11-05 12:14 UTC, lena-lis approved these changes

2024-11-05 12:14 UTC, IvanBelikov requested changes

2024-11-05 12:14 UTC, IvanBelikov commented on src/components/createUser/CreateUser.tsx
> +              onChange={(e) => setUserId(Number(e.target.value))}
Поле с выбором id для юзера не нужно

2024-11-05 12:14 UTC, IvanBelikov commented on src/components/createUser/CreateUser.tsx
> +  }
Лучше вынести в один стейт, например userForm. Это будет объект с аналогичными полями.

2024-11-05 12:14 UTC, IvanBelikov commented on src/components/createUser/CreateUser.tsx
> +    resetAll()
Для работы с асинхронными запросами мы используем синтаксис async/await.

2024-11-05 12:15 UTC, IvanBelikov requested changes
Добавить обработку свойства loading и error.

2024-11-05 16:09 UTC, Sparkell72 approved these changes

2024-11-06 14:13 UTC, clue1essdev commented on src/components/createUser/CreateUser.tsx
> +              onChange={(e) => setUserId(Number(e.target.value))}
Поле id удалено вместе с полем роли (поскольку сервер их не принимает)

2024-11-06 14:13 UTC, clue1essdev commented on src/components/createUser/CreateUser.tsx
> +  }
Стейты заменены на хук useForm

2024-11-06 14:13 UTC, clue1essdev commented on src/components/createUser/CreateUser.tsx
> +    resetAll()
Сделал

2024-11-06 14:13 UTC, clue1essdev commented
Поменял логику компонента, добавил обработку загрузки / ошибки / успеха

2024-11-06 16:11 UTC, gineff commented on src/components/createUser/CreateUser.tsx
> +      <Box>
иконка здесь лишняя

2024-11-06 18:13 UTC, clue1essdev commented on src/components/createUser/CreateUser.tsx
> +const CreateUser: React.FC = observer(() => {
я его и использовал

2024-11-06 18:14 UTC, clue1essdev commented on src/components/createUser/CreateUser.tsx
> +      <Box>
Почему? Мне кажется, она делает UI более понятным

2024-11-06 18:19 UTC, clue1essdev commented on src/router/routes.tsx
> +        path: ROUTES.admin('create-user'),
сделал

2024-11-06 18:29 UTC, IvanBelikov approved these changes

2024-11-06 19:55 UTC, merged