Feature/create document form changes
CaseLabJS/CaseLab2024-team1 pull request #30
Opened 2024-11-06 12:58 UTC by glush-chenko

- Удалены примеры для историй
- Тестовые данные перемещены, поправлены все ошибки по prettier и lint 
- Добавлен page container

2024-11-06 20:06 UTC, Slumrag commented on src/components/appDashboardLayout/page/page.tsx
Мне кажется, стоит этот компонент назвать ColumnLayout.

2024-11-06 20:26 UTC, Slumrag commented on src/components/createDocumentForm/createDocumentForm.tsx
>      console.log('data', data)
стоит log убрать

2024-11-06 20:35 UTC, Slumrag reviewed
На мобильной ширине инпут вылезает за границу формы.
![image](https://github.com/user-attachments/assets/5a118718-ad80-4cdc-aec3-08a584df9b6d)

2024-11-07 09:28 UTC, IvanBelikov submitted a review, later dismissed
Текущий компонент создания документа является заглушкой. Полагаю, что функционал компонента будет строиться на основе функционала соответствующего стора.

Считаю изменения в компоненте создания документа бесмысленными. (Опять, так как сейчас он является заглушкой и не отвечает требованиям реального компонента, который будет создан на основе стора)

Предлагаю закрыть пул реквест и направить силы на разработу стора по работе с документами т.к. он первичнее.

2024-11-07 13:28 UTC, glush-chenko commented on src/components/appDashboardLayout/page/page.tsx
> Мне кажется, стоит этот компонент назвать ColumnLayout или SingleColumnLayout. Из названия Page создаётся впечатление, что это какой-то сложный компонент, а не просто div с отступами.

как насчет PageContainer?

2024-11-07 13:48 UTC, glush-chenko commented
> Текущий компонент создания документа является заглушкой. Полагаю, что функционал компонента будет строиться на основе функционала соответствующего стора.
> 
> Считаю изменения в компоненте создания документа бесмысленными. (Опять, так как сейчас он является заглушкой и не отвечает требованиям реального компонента, который будет создан на основе стора)
> 
> Предлагаю закрыть пул реквест и направить силы на разработу стора по работе с документами т.к. он первичнее.

в данном ПР исправляется форматирование и типизация, что относится к задаче по форме, которую я получила в свою первую неделю. 
Форма основана на тестовых данных, которые соответствуют типам, приходящим с сервера. Он не является заглушкой. Стор по документам почти готов, жду, пока примут пиар с обновленной информацией по комментариям. 
Задача на подключение стора к форме документа- отдельная задача 
https://github.com/users/CaseLabJS/projects/1/views/1?pane=issue&itemId=86087853

2024-11-07 14:25 UTC, glush-chenko commented
> На мобильной ширине инпут вылезает за границу формы. ![image](https://private-user-images.githubusercontent.com/85808787/383716968-5a118718-ad80-4cdc-aec3-08a584df9b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODkxNDMsIm5iZiI6MTczMDk4ODg0MywicGF0aCI6Ii84NTgwODc4Ny8zODM3MTY5NjgtNWExMTg3MTgtYWQ4MC00Y2RjLWFlYzMtMDhhNTg0ZGY5YjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE0MTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZmU1YzUzMjIxNjZhZjVlNWZlODU0NDRhY2VkZjMxNWU1ZGJjMmYzMGUzNjc5ZWE3YzFmZWQxMWFlY2I0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yTnDnbuY2ferosFu31IiKgIWmDwBOYHN98o80SU7JtI)

поправила

2024-11-08 14:06 UTC, lena-lis approved these changes

2024-11-08 14:58 UTC, glush-chenko commented on src/components/createDocumentForm/createDocumentForm.tsx
>      console.log('data', data)
> стоит log убрать

убрала

2024-11-10 18:44 UTC, gineff commented
![Vite-React-TS-11-10-2024_02_01_PM](https://github.com/user-attachments/assets/9fa246d5-9351-4c1d-afde-344359ee718d)
![Vite-React-TS-11-10-2024_01_58_PM](https://github.com/user-attachments/assets/b7fe8b77-de4f-42f3-935b-d81e56bee963)

2024-11-10 18:45 UTC, gineff requested changes
![Vite-React-TS-11-10-2024_02_01_PM](https://github.com/user-attachments/assets/528b848f-ba6c-4899-97d3-1836c4683e9e)
![Vite-React-TS-11-10-2024_01_58_PM](https://github.com/user-attachments/assets/371b6ad8-cfea-4fa7-8665-31e06e977a34)

2024-11-10 19:19 UTC, glush-chenko commented
> ![Vite-React-TS-11-10-2024_02_01_PM](https://private-user-images.githubusercontent.com/9252601/384717852-528b848f-ba6c-4899-97d3-1836c4683e9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNjYzNjYsIm5iZiI6MTczMTI2NjA2NiwicGF0aCI6Ii85MjUyNjAxLzM4NDcxNzg1Mi01MjhiODQ4Zi1iYTZjLTQ4OTktOTdkMy0xODM2YzQ2ODNlOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMTkxNDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFlYmUxNzIyZGRiNWRmN2Y1OGUyNzVhZjgzMjgwZjE0MzJiNjg5OWU1YWY1NGQxMTg5NjIyYjkwMmQ2YzVkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.sCLPzMK7xlp4dsjztgsbJzeSc3hm3PfxydGB6Yd26vw) ![Vite-React-TS-11-10-2024_01_58_PM](https://private-user-images.githubusercontent.com/9252601/384717854-371b6ad8-cfea-4fa7-8665-31e06e977a34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNjYzNjYsIm5iZiI6MTczMTI2NjA2NiwicGF0aCI6Ii85MjUyNjAxLzM4NDcxNzg1NC0zNzFiNmFkOC1jZmVhLTRmYTctODY2NS0zMWUwNmU5NzdhMzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMTkxNDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmRkYjFhZjExODkxOWVmNjE0NmI3MGQ4MTg2YWIyMGZlNTFkMGMzNGM1YzIzNTAwYTA1MGIxMDI1NTk5NDA0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WzZXmnDD7iD7cFjVqydHYvucdRplL8IkoH_4jHv8PPY)

это не относится к этому ПР, здесь только исправления форматирования и lint ошибок.

2024-11-15 10:50 UTC, clue1essdev approved these changes

2024-11-15 12:26 UTC, merged