docs: :memo: update README
CaseLabJS/CaseLab2024-team1 pull request #32
Opened 2024-11-06 18:55 UTC by Slumrag

Обновил README

2024-11-06 22:33 UTC, IvanBelikov commented on README.md
> +В корневой папке проекта создадим файл .env.development, содержащий переменные окружения.
Можно уточнить, что по примеру файлу .env.development.example

2024-11-06 22:35 UTC, IvanBelikov requested changes

2024-11-06 22:35 UTC, IvanBelikov commented on README.md
> +Для установки и запуска проекта, необходим [NodeJS](https://nodejs.org/) v22.10+.
Всё супер. Единственный момент версия ноды нужна именно 22.10

2024-11-06 22:36 UTC, IvanBelikov commented on README.md
> +Для установки и запуска проекта, необходим [NodeJS](https://nodejs.org/) v22.10+.
Либо уточнить, что крайне рекомендуется именно нода 22.10

2024-11-07 05:45 UTC, gineff approved these changes

2024-11-07 11:01 UTC, Slumrag commented on README.md
> +В корневой папке проекта создадим файл .env.development, содержащий переменные окружения.
Мне кажется это дублирующая информация и может запутать читателя. Лучше напрямую написать что точно должно быть в файле env.development, чтобы не было двойных трактовок.

2024-11-07 11:02 UTC, Slumrag commented on README.md
> +Для установки и запуска проекта, необходим [NodeJS](https://nodejs.org/) v22.10+.
Поправлю

2024-11-07 11:31 UTC, IvanBelikov approved these changes

2024-11-08 14:19 UTC, lena-lis approved these changes

2024-11-08 14:25 UTC, merged