documents store
CaseLabJS/CaseLab2024-team1 pull request #45
Opened 2024-11-10 10:58 UTC by glush-chenko

- добавлен DocumentStore и DocumentsListStore
- методы delete и recover дополнительно обрабатываются и возвращают boolean

2024-11-10 13:17 UTC, IvanBelikov requested changes

2024-11-10 19:40 UTC, gineff requested changes

2024-11-10 19:40 UTC, gineff commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +      documentControllerApi.getDocuments()
в качестве аргумента нужно передать объект, включающий поля type QueryParams: showOnlyAliv, page,   size, ascending

2024-11-10 19:40 UTC, gineff commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +      documentControllerApi.getDocumentById(documentId)
в качестве второго аргумента нужно передать объект, включающий поле showOnlyAlive

2024-11-10 19:40 UTC, gineff commented on src/stores/DocumentStore/DocumentStore.ts
> +        documentControllerApi.recover(this.documentData.id)
вероятно, дополнительно нужно загрузить восстановленный документ с сервера по id, и добавить этот документ в this.documents

2024-11-10 19:40 UTC, gineff commented on src/stores/DocumentStore/DocumentStore.ts
> +    const createDocumentVersion = await executeWithLoading(this, () =>
наименование переменной createdDocumentVersion более соответствует значению переменной

2024-11-10 19:40 UTC, gineff commented on src/stores/DocumentStore/DocumentStore.ts
> +      this.documentData = {
![image](https://github.com/user-attachments/assets/c7ac94b6-0af2-4f08-a309-9fa52e8bf0d7)

2024-11-10 21:35 UTC, glush-chenko commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +    }
поправила

2024-11-10 21:35 UTC, glush-chenko commented on src/stores/DocumentStore/DocumentStore.ts
> +
поправила

2024-11-10 21:36 UTC, glush-chenko commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +      this.documents = fetchedDocuments.map(
поправила

2024-11-10 21:39 UTC, glush-chenko commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +  async fetchDocuments() {
изменила на стрелочные функции

2024-11-10 21:52 UTC, glush-chenko commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +    return await executeWithLoading(this, async () =>
поправила

2024-11-10 21:54 UTC, glush-chenko commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +      documentControllerApi.getDocuments()
добавила

2024-11-10 21:55 UTC, glush-chenko commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +      documentControllerApi.getDocumentById(documentId)
добавила

2024-11-10 21:55 UTC, glush-chenko commented on src/stores/DocumentStore/DocumentStore.ts
> +    const createDocumentVersion = await executeWithLoading(this, () =>
наименовала

2024-11-10 21:55 UTC, glush-chenko commented on src/stores/DocumentStore/DocumentStore.ts
> +      this.documentData = {
поправила

2024-11-10 22:03 UTC, glush-chenko commented on src/stores/DocumentStore/DocumentStore.ts
> +        documentControllerApi.recover(this.documentData.id)
не уверена, зависит от того, как мы хотим реализовывать recover функциональность. К примеру, если мы будем отображать список удаленных документов (чтобы пользователь мог восстановить один из них), то, вероятнее всего, этот документ уже будет присутствовать в documentsListStore.documents

2024-11-10 22:20 UTC, glush-chenko commented
Вероятно, всем так же стоит поправить это в своих сторах
https://github.com/CaseLabJS/CaseLab2024-team1/pull/45#discussion_r1835729235
https://github.com/CaseLabJS/CaseLab2024-team1/pull/45#discussion_r1835735480
https://github.com/CaseLabJS/CaseLab2024-team1/pull/45#discussion_r1835761910
https://github.com/CaseLabJS/CaseLab2024-team1/pull/45#discussion_r1835762106

2024-11-11 10:02 UTC, gineff approved these changes

2024-11-11 11:34 UTC, IvanBelikov approved these changes

2024-11-11 18:29 UTC, IvanBelikov requested changes

2024-11-11 18:29 UTC, IvanBelikov commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +}
Если запрос корректно не обработается на сервере, интерфейс при текущей реализации всё равно будет удалять пользователя из списка. Для проверки успешности обработки запроса нужно проверять свойство this.error на null и только затем изменять значения this.documents.

2024-11-11 18:30 UTC, IvanBelikov commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +    }
Лишняя проверка, достаточно будет отправить запрос и обработать ответ от сервера.

2024-11-12 00:39 UTC, glush-chenko commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +    }
> Лишняя проверка, достаточно будет отправить запрос и обработать ответ от сервера.

зачем делать лишний запрос на сервер, если документа может и не быть?

2024-11-12 00:49 UTC, glush-chenko commented on src/stores/DocumentsListStore/DocumentsListStore.ts
> +}
добавила. Вероятно, стоит это сделать в остальных сторах тоже

2024-11-12 09:56 UTC, IvanBelikov approved these changes

2024-11-12 15:52 UTC, merged