Feature/add user deletion button
CaseLabJS/CaseLab2024-team1 pull request #46
Opened 2024-11-10 20:20 UTC by tv-tugova

1) Добавлена новая колонка с действиями (сейчас там удаление юзера, позже будет иконка для редактирования юзера)
2) Реализована функциональность удаления пользователя с подтверждением через всплывающее окно

2024-11-11 13:03 UTC, lena-lis approved these changes

2024-11-11 18:05 UTC, IvanBelikov commented
![image](https://github.com/user-attachments/assets/f2de9706-dc06-472a-8657-a924e0421aea)
Не относится конкретно к этому PR, но лучше вынести данный объект в отдельный файл config.ts внутри этой же папки с компонентом.

2024-11-11 18:23 UTC, IvanBelikov requested changes

2024-11-11 18:23 UTC, IvanBelikov commented on src/components/userTable/UserTable.tsx
> +      </Popover>
Лучше вынести данную реализацию поп ап в отдельный компонент, пропсами можно прокидывать заголовок и коллбэк, который будет вызываться при подтверждении.

2024-11-11 18:23 UTC, IvanBelikov commented on src/components/userTable/UserTable.tsx
> +        <Box sx={{ display: 'flex', justifyContent: 'space-around' }}>
Можно добавить свойство width: `'fit-content'`, тогда экшоны не будут разъезжаться

![image](https://github.com/user-attachments/assets/59da61b3-6249-4ac3-a031-80acae88639b)

2024-11-11 21:06 UTC, tv-tugova commented on src/components/userTable/UserTable.tsx
> +        <Box sx={{ display: 'flex', justifyContent: 'space-around' }}>
добавила

2024-11-11 21:07 UTC, tv-tugova commented on src/components/userTable/UserTable.tsx
> +      </Popover>
Вынесла

2024-11-11 21:07 UTC, tv-tugova commented
@IvanBelikov Пока не буду создавать config.ts, так как это код не переиспользуется и мне нагляднее, когда он находится в UserTable

2024-11-12 06:48 UTC, clue1essdev commented on src/components/userTable/UserTable.tsx
>      navigate('/admin/users/create')
Здесь лучше navigate(ROUTES.admin('users/create')), чтобы уменьшить количество hardcoded values

2024-11-12 06:49 UTC, clue1essdev commented on src/components/userTable/UserTable.tsx
> +  }
Здесь хорошо бы работать с ошибкой и loading из стора, уведомлять пользователя о загрузке/ошибке/успехе

2024-11-12 09:59 UTC, IvanBelikov commented on src/components/userTable/UserTable.tsx
> +        title="Вы уверены?"
`title="Вы уверены?"` является магическим значением. Такие штуки тоже стоит выносить в отдельный конфиг.
`title=config.confirmMessage`

2024-11-12 10:00 UTC, IvanBelikov approved these changes

2024-11-12 10:02 UTC, IvanBelikov commented on src/components/userTable/UserTable.tsx
> +        title="Вы уверены?"
Такой подход сразу закладывает возможность удобной реализации i18n при необходимости.

2024-11-12 12:29 UTC, tv-tugova commented on src/components/userTable/UserTable.tsx
>      navigate('/admin/users/create')
Поправила

2024-11-12 12:35 UTC, clue1essdev approved these changes

2024-11-12 12:43 UTC, merged