integrate attributeListStore, decompose component CreateAttributeForm in new branch
CaseLabJS/CaseLab2024-team1 pull request #64
Opened 2024-11-14 18:08 UTC by AlphaRasch

2024-11-18 13:56 UTC, clue1essdev commented on src/pages/CreateAttributePage/components/Success/index.tsx
> +})
В MUI для этого есть Snackbar с Alert внутри (у Alert есть пропс severity="error" / severity="success"), то есть логику обработки ошибки успеха можно уместить в один компонент и лучше перенести на уровень выше (поскольку в компонентах всего по 8-10 строк, со снекбаром будет меньше / столько же, но логика в одном месте), образец в signInForm и createUser и наверное уже и в некоторых других компонентах. Помимо этого, не нужно будет использовать html-верстку (у нас вроде по всему приложению 95% (если не 100) - это MUI-компоненты
![image](https://github.com/user-attachments/assets/043892d9-77a3-4492-99e3-3002c367f1d4)
![image](https://github.com/user-attachments/assets/cd521f06-13fd-47ec-8c17-058fa5a58be1)

2024-11-18 14:11 UTC, AlphaRasch commented on src/pages/CreateAttributePage/components/Success/index.tsx
> +})
Хорошо подправлю данный момент

2024-11-21 06:57 UTC, clue1essdev approved these changes

2024-11-22 13:37 UTC, glush-chenko approved these changes

2024-11-26 11:52 UTC, IvanBelikov requested changes
![image](https://github.com/user-attachments/assets/85fb34a2-74ed-4637-9522-22b325acd973)
Не очень хорошо, что можно повесить атрибут на один и тот же тип неограниченное кол-во раз. Нужно поправить этот момент.

2024-12-03 13:44 UTC, closed without merging