Обновления api endpoints
CaseLabJS/CaseLab2024-team1 pull request #76
Opened 2024-11-21 13:20 UTC by gineff

Добавлены методы api
- getDocumentsCount
- getVotes
- signDocumentByAuthor

2024-11-22 13:34 UTC, glush-chenko requested changes
в MobX рекомендуется избегать методов, которые изменяют массивы или объекты напрямую, таких как push, и вместо этого использовать иммутабельные подходы для обновления состояния.
Это относится к getSignatureRequestById, createSignatureRequest

2024-11-22 13:34 UTC, glush-chenko commented on src/stores/SignatureListStore/SignatureListStore.ts
> +  async signDocumentByAuthor(
лучше бы было, конечно, использовать стрелочные функции чтобы избежать потери this
из-за этого нельзя использовать const { fetchSignatureRequests } = signatureListStore и другие функции

2024-11-23 05:35 UTC, gineff commented
> в MobX рекомендуется избегать методов, которые изменяют массивы или объекты напрямую, таких как push, и вместо этого использовать иммутабельные подходы для обновления состояния. Это относится к getSignatureRequestById, createSignatureRequest

MobX рекомендуется избегать методов, которые изменяют массивы или объекты напрямую, ***без использования специальных методов или реактивных механизмов, предоставляемых MobX*** 
В getSignatureRequestById, createSignatureRequest использован **runInAction**

2024-11-23 09:27 UTC, IvanBelikov approved these changes

2024-11-24 04:30 UTC, glush-chenko commented
> > в MobX рекомендуется избегать методов, которые изменяют массивы или объекты напрямую, таких как push, и вместо этого использовать иммутабельные подходы для обновления состояния. Это относится к getSignatureRequestById, createSignatureRequest
> 
> MobX рекомендуется избегать методов, которые изменяют массивы или объекты напрямую, _**без использования специальных методов или реактивных механизмов, предоставляемых MobX**_ В getSignatureRequestById, createSignatureRequest использован **runInAction**

тем не менее, для повышения предсказуемости и удобства работы с состоянием рекомендуется следовать иммутабельным подходам, которые уже реализованы в других сторах до этого. Ваш выбор остается за вами

2024-11-24 04:31 UTC, glush-chenko approved these changes

2024-11-25 18:46 UTC, lena-lis approved these changes

2024-11-26 05:01 UTC, merged