Feature/createDocumentTypePage
CaseLabJS/CaseLab2024-team1 pull request #78
Opened 2024-11-24 11:12 UTC by Sparkell72

Страница создания типа документа. В компоненте есть обязательное поле "Название типа документа" которое обязательно при создании, так же на выбор даются атрибуты, которые передают информацию на сервер.
![image](https://github.com/user-attachments/assets/1939979f-99a7-4929-9759-69320516cc5f)

2024-11-24 11:57 UTC, IvanBelikov commented
Кнопку "Вернуться назад", вероятно, тоже стоит убрать т.к. переход на страницу создания типа осуществлеяется через админку и не связана с формой создания документа.

2024-11-24 11:57 UTC, IvanBelikov requested changes

2024-11-24 11:57 UTC, IvanBelikov commented on src/router/routes.tsx
> +        path: ROUTES.admin('create-document/type'),
Считаю, путь стоит сменить на `document-type` или `create-document-type`

2024-11-24 15:07 UTC, Sparkell72 commented on src/router/routes.tsx
> +        path: ROUTES.admin('create-document/type'),
Поменял

2024-11-24 15:08 UTC, Sparkell72 commented on src/router/routes.tsx
> +        path: ROUTES.admin('create-document/type'),
Считаю, что кнопку надо оставлять, поскольку надо будет возвращаться на ту форму, от которой мы перешли на создание.

2024-11-24 15:09 UTC, Sparkell72 commented
Был изменен Rout на document-type.

2024-11-24 15:32 UTC, clue1essdev commented on .vscode/extensions.json
> +}
Это надо убрать. что это вообще?

2024-11-24 15:33 UTC, clue1essdev commented on src/components/createDocumentTypePage/createDocumentTypePage.tsx
> +  }, [])
Можно просто вызвать метод стора с void в useEffect, try-catch блоки не нужны, поскольку они заложены в АПИ / сторы

2024-11-24 15:34 UTC, clue1essdev commented on src/router/routes.tsx
>        },
здесь route должен быть более понятным, например, document-types/create

2024-11-26 11:50 UTC, IvanBelikov requested changes
![image](https://github.com/user-attachments/assets/85fb34a2-74ed-4637-9522-22b325acd973)
Не очень хорошо, что можно повесить атрибут на один и тот же тип неограниченное кол-во раз. Нужно поправить этот момент.

2024-11-26 11:54 UTC, IvanBelikov requested changes
Работает ок, но нужно поправить замечания от Тамерлана

2024-11-26 13:58 UTC, clue1essdev commented on src/router/routes.tsx
> +        path: ROUTES.admin('create-document/type'),
Кнопку надо убрать из-за того, как у нас реализована навигация. В форме создания пользователя также эту кнопку уберу

2024-11-29 06:35 UTC, clue1essdev approved these changes

2024-11-29 10:25 UTC, IvanBelikov approved these changes

2024-11-29 11:32 UTC, lena-lis approved these changes

2024-11-30 15:01 UTC, merged