feat: :sparkles: initial mobx stores implemented
CaseLabJS/CaseLab2024-team1 pull request #8
Opened 2024-10-24 14:39 UTC by tv-tugova

2024-10-24 18:38 UTC, IvanBelikov commented on src/stores/TestStore.ts
Если я правильно понял, это просто тестовый стор. В таком случае его не стоит мерджить.

2024-10-24 18:43 UTC, IvanBelikov commented
Общее предложение по организации стора: создать общий стор RootStore, который нужен для доступа ко всем остальным сторам приложения. Создать контекст для данного стора и хук useStores, чтобы иметь к ним более удобный доступ без надобности каждый раз импортировать сторы в файл.

2024-10-25 06:59 UTC, gineff commented
Мне напротив, кажется не строит усложнять работу со стором.  RootStore нужен, если использовать провайдер, здесь же mobx-react-lite и провайдер не нужен. Самое простое и естественное решение - импорт нужного стора

2024-10-25 07:24 UTC, tv-tugova commented
Тестовый стор я уберу. А раз насчет RootStore мнения разошлись, можно сделать голосование в общей беседе.

2024-10-25 13:57 UTC, gineff approved these changes

2024-10-25 13:59 UTC, clue1essdev approved these changes

2024-10-25 16:28 UTC, IvanBelikov requested changes
Нужно поправить форматирование с помощью Prettier.

2024-10-25 18:35 UTC, IvanBelikov approved these changes

2024-10-26 16:23 UTC, Slumrag approved these changes

2024-10-26 16:30 UTC, glush-chenko approved these changes

2024-10-26 17:49 UTC, merged